### ISSUE TITLE
 Vtune and unable to find via

### ISSUE THREAD

**Issue by 04github** [asyncvlsi/SPRoute#2]
I got "unable to find via: " and "WARNING: Vtune not enabled or found" when running SPRoute. Will they affect the result? If yes, how can I fix them?

**Comment by Michael-JY-He** [comment]
Could you send me the complete printing log? 
The WARNING will not affect the result.

**Comment by 04github** [comment]
The log of ispd19_test8 is [here](https://sharetext.me/aurwetys4j).

**Comment by Michael-JY-He** [comment]
It is a bug and fixed now. Please pull both the latest phyDB and SPRoute. 
Note that if you want to run the performance number of SPRoute, please contact me for a standalone version of SPRoute. Thanks.

**Comment by 04github** [comment]
Thank you. It works well. Is it correct to use "-algo Det" to run SPRoute?

**Comment by Michael-JY-He** [comment]
Yes. Det is correct. 
Det is deterministic. NonDet is non-deterministic but faster.

**Comment by 04github** [comment]
Thanks for your explanation.
I ran SPRoute with Det and got a score of 90706226 for ispd19_test7, which is quite far away from what is shown in the paper. What do you think are some possible reasons?

**Comment by Michael-JY-He** [comment]
This might take some time to fix. Can you email me (hejiayuan19920229@gmail.com) so that I can share the standalone SPRoute with you?
